### PR TITLE
[WR-989-995] adds Request a Tour Stop form link and popup

### PR DESCRIPTION
**Pull request by anuragparihar1**

### CODE REVIEW

**Review by rjkuyvenhoven — COMMENTED** [review]
The link text should match the wireframe, each word capitalized with the arrow head icon.

**Comment by rjkuyvenhoven** [comment]
There should have already been a solution for the Collection Notice link.  There is a block that provides this link for the Contact Us and Request a Tour Stop form pages. I'm not sure why it is not showing on the Request a Tour Stop page.

**Comment by rjkuyvenhoven** [comment]
The popup message I get when I click the "Privacy Policy" link is inconsistent with the action.

"This job posting is on another organization’s job board. By continuing, you will be directed to the original posting at www2 gov bc"

**Comment by anuragparihar1** [comment]
> 

Do you have the latest copy of the development branch? We had this bug long ago where each external link was showing this popup but was resolved. Try clicking the privacy link in the footer and see what you get.

**Comment by rjkuyvenhoven** [comment]
I was testing against this branch.  I get the same message when I click on the privacy link in the footer.  I also tested with the latest version of develop branch and get the same message when clicking the privacy link in the footer.

**Comment by rjkuyvenhoven** [comment]
I have re-tested the Privacy Policy link after clearing cache and a hard refresh and the link works as expected.

**Comment by anuragparihar1** [comment]
> The link text should match the wireframe, each word capitalized with the arrow head icon.

Fixed, Please check.

**Review by rjkuyvenhoven — APPROVED** [review]
lgtm

**Pull request merged**
