### PR TITLE
WR-1737 update chart styling

### PR DESCRIPTION
**Pull request by rjkuyvenhoven**

### CODE REVIEW

**Comment by rjkuyvenhoven** [comment]
British-Columbia-WorkBC
Vancouver-Island-Coast-WorkBC
Agriculture-and-Fishing-WorkBC
Accommodation-travel-tourism-WorkBC

**Comment by infojunkie** [comment]
I see that the labels are still not showing the values... we'll need to get approval from the client or propose an alternative.

**Comment by infojunkie** [comment]
I've found the setting to add the value to the legend label - please apply where needed and update the screenshots. We'll use that version to seek approval.

**Comment by rjkuyvenhoven** [comment]
BC Profile
WorkBC-BC-Profile

Region Profile
WorkBC-Region-Profile

Career Profile
WorkBC-Career-Profile

**Comment by rjkuyvenhoven** [comment]
updated pie charts

BC Profile
British-Columbia-WorkBC (1)

Region Profile
Regional-Profile-WorkBC

Career Profile
Career-profile-WorkBC

**Review by infojunkie — APPROVED** [review]
Lgtm, thanks

**Pull request merged**
