### PR TITLE
[WR-1486] fix-spacing-before-recent-job-on-mobile

### PR DESCRIPTION
**Pull request by jonathan-longe**
The client provided the following screenshot showing too much white space prior to the "Recent Jobs" block.
Prod recent jobs spacing

The following screenshots illustrates the fixes on each of the pages shown above.

### BC Profile
BC_profile

### Regional Profile
regional_profile

### Industry Profile
industry_profile

### Career Profile
career-profile

### Career Profile with Video
career-profile-video

### CODE REVIEW

**Review by infojunkie — CHANGES_REQUESTED** [review]
I note that the space between career videos and recent jobs (last screenshot) is less than everywhere else. I would suggest ensurings it remains equal to the others.

**Comment by jonathan-longe** [comment]
> I note that the space between career videos and recent jobs (last screenshot) is less than everywhere else. I would suggest ensurings it remains equal to the others.

Good eye @infojunkie I've increased the spacing as suggested.  
Screenshot from 2023-08-09 14-57-38

**Comment by jonathan-longe** [comment]
FYI, my initial commit to this PR quoted the incorrect Jira ticket number.  I've corrected the commit and force pushed an update to Github.  The fix for the spacing issue that @infojunkie requested is incorporated into the initial commit.

**Review by infojunkie — APPROVED** [review]
Lgtm, thanks

**Pull request merged**
