### PR TITLE
[WR-1357] add responsive region employment table

### PR DESCRIPTION
**Pull request by jonathan-longe**
On small devices, the BC employment table stats used to look like this:

image

The client requested a responsive table design that looks like this when the screen is too small to display the table properly:

image

Now, when the screen width is greater than 600px, the table is displayed like this (no change):
Screenshot from 2023-07-28 10-25-15

And, when the screen width is smaller than 600px, the table displayed like this:
Screenshot from 2023-07-28 10-25-58

### CODE REVIEW

**Comment by infojunkie** [comment]
I can't see the "after" screenshots, @jonathan-longe

**Comment by jonathan-longe** [comment]
> I can't see the "after" screenshots, @jonathan-longe

Apologies, I've added them now.

**Comment by infojunkie** [comment]
Thanks! I see an information icon missing on your responsive screenshot, as compared to the wireframe.

**Comment by jonathan-longe** [comment]
> Thanks! I see an information icon missing on your responsive screenshot, as compared to the wireframe.

Ah, well spotted. Where do I find out more about what's the expected behavior of the information icon?

**Comment by jonathan-longe** [comment]
Hard coded the definition of "unemployment rate" in the template

image

Placed the information icon adjacent to the title so it is consistent with the placement of the other information icons on the page.

**Comment by jonathan-longe** [comment]
In the small screen view, the information icon is temporarily shown adjacent to the "Employment by Region" title for consistency with the block below.  When the BC map is added (future ticket) the information icon can be moved below the map.  

Screenshot from 2023-07-28 15-32-04

**Comment by jonathan-longe** [comment]
The "BC Average" summary row is now shown with the correct background colour in the small screen view

Screenshot from 2023-07-28 15-47-47

**Review by infojunkie — APPROVED** [review]
Looks good now! thanks

**Pull request merged**
