### PR TITLE
[WR-1721] make BC map on labour market update responsive

### PR DESCRIPTION
**Pull request by jonathan-longe**
This PR makes the BC map and table on the "labour market update" responsive to mobile users.

Screenshot from 2023-08-16 09-43-50

Screenshot from 2023-08-16 09-44-29

### CODE REVIEW

**Comment by rjkuyvenhoven** [comment]
These changes look good. However, there are 5 interactive maps/tables on the site.  The Labour Market Update page, 2 on the Career Profile pages, BC Profile page and the Industry Profile pages. The changes you've made for the Career Profile and Labour Market Update maps/tables have resulted in the row highlighting on the BC Profile and Industry Profile pages to stop working on alternate rows.

I suggest updating the tables on BC Profile and Industry profile pages to match the Career Profile and Labour Market Update pages.  This will make things consistent across the site.

**Comment by jonathan-longe** [comment]
> These changes look good. However, there are 5 interactive maps/tables on the site. The Labour Market Update page, 2 on the Career Profile pages, BC Profile page and the Industry Profile pages. The changes you've made for the Career Profile and Labour Market Update maps/tables have resulted in the row highlighting on the BC Profile and Industry Profile pages to stop working on alternate rows.
> 
> I suggest updating the tables on BC Profile and Industry profile pages to match the Career Profile and Labour Market Update pages. This will make things consistent across the site.

Ah, well spotted, @rjkuyvenhoven .  I'll merge the other PR I have into this one and confirm that all map pages are working correctly.

**Comment by jonathan-longe** [comment]
Here's a list of all the pages with an interactive map:

- [ ] http://workbc.docker.localhost:8000/research-labour-market/bcs-economy/labour-market-monthly-update
- [ ]  http://workbc.docker.localhost:8000/industry-profile/accommodation-and-food-services LMS Tab
- [ ]  http://workbc.docker.localhost:8000/career-profiles/registered-nurses-and-registered-psychiatric-nurses LMS Tab - 2 maps to check
- [ ]  http://workbc.docker.localhost:8000/region-profile/british-columbia LMS Tab

**Review by rjkuyvenhoven — APPROVED** [review]
lgtm, thanks!

**Pull request merged**
