### PR TITLE
WR 1509  search highlighting

### PR DESCRIPTION
**Pull request by rjkuyvenhoven**

### CODE REVIEW

**Comment by infojunkie** [comment]
I tested the PR locally and I can see the highlights! Great job. 

One comment: Looking at http://workbc.docker.localhost:8000/admin/config/search/search-api/server/solr, I can still see the message:

```Solr is using an outdated [configset](https://solr.apache.org/guide/solr/latest/configuration-guide/config-sets.html), created with a version of Search API Solr older than 4.3.0. Please follow the instructions in the [README.md](http://workbc.docker.localhost:8000/modules/contrib/search_api_solr/README.md) file, to create and deploy a fresh set of Solr configuration files, based on the currently installed version of Search API Solr.```

What are the steps needed to update the solr schema to the config in this PR ?

**Comment by rjkuyvenhoven** [comment]
After updating the configuration I did a docker compose down and up and that cleared up the message.

**Comment by infojunkie** [comment]
Thanks, worked for me too.

**Review by infojunkie — APPROVED** [review]
Lgtm, thanks!

**Pull request closed without merging**
