### PR TITLE
WR-1361 half width icon cards

### PR DESCRIPTION
**Pull request by rjkuyvenhoven**

### CODE REVIEW

**Comment by infojunkie** [comment]
Thanks @rjkuyvenhoven I will download and test this locally as well.

**Comment by infojunkie** [comment]
Works well for me. One question to @jonathan-longe: The cards without bottom links look the attached. Is there any explicit expectation about this case (e.g. to center the icon / text) ? If not indicated in the ticket, no need to bring it up.

screenshot-workbc docker localhost_8000-2023 09 20-12_22_52

**Comment by jonathan-longe** [comment]
> Works well for me. One question to @jonathan-longe: The cards without bottom links look the attached. Is there any explicit expectation about this case (e.g. to center the icon / text) ? If not indicated in the ticket, no need to bring it up.

@infojunkie good question! I'm not aware of such a requirement.  Every example in the wireframes includes a link in the footer.  I'd suggest we leave it as is and adjust in the future if necessary.

**Comment by infojunkie** [comment]
Sounds good, thanks @jonathan-longe

**Pull request closed without merging**
