### PR TITLE
Adds fvm module and gives content editor ability to set viewmode of a…

### PR DESCRIPTION
**Pull request by anuragparihar1**
… page

Please check

### CODE REVIEW

**Comment by infojunkie** [comment]
Why do we need to give editor ability to change the viewmode? If this is related to the calendar page theming, we only need to specify a different viewmode, but not expose this ability to editors.

**Comment by anuragparihar1** [comment]
@infojunkie We need some way of telling Drupal which node would use the different viewmode.  [ fvm module](https://www.drupal.org/project/fvm) is used to change the viewmode. If needed we can either disable the field in the Form Display or not give the content editor access to this field. Suggestions?

**Comment by infojunkie** [comment]
Right, I was just not expecting a full module needed for that. No need to expose that field to other than full admins.

**Comment by anuragparihar1** [comment]
@infojunkie Field disabled in the Form Display to secure access.

**Review by infojunkie — APPROVED** [review]
Thanks, looks good to me now.

**Pull request merged**
