### PR TITLE
[WR-1070] fix mobile tile display - version 2

### PR DESCRIPTION
**Pull request by jonathan-longe**
Further changes as requested by Sai

### CODE REVIEW

**Comment by infojunkie** [comment]
Can you include a screenshot from BrowserStack that this fixes the failure report?

**Comment by jonathan-longe** [comment]
> Can you include a screenshot from BrowserStack that this fixes the failure report?

Good call. See below. Note, not all iPad's will display a single tile in portrait mode. The number of tiles displayed is dependent on screen width.

image

**Review by infojunkie — COMMENTED** [review]
Looking at this change, I wonder how the 3 tiles were still showing in portrait mode. Shouldn't it have been 2 tiles only?

**Comment by jonathan-longe** [comment]
> Looking at this change, I wonder how the 3 tiles were still showing in portrait mode. Shouldn't it have been 2 tiles only?

There were two tiles displayed previously, but they were broken up like this:  0.5 tile + 1 tile + 0.5 tile = 2 tiles.

**Comment by infojunkie** [comment]
Thanks for the explanation - lgtm, thanks!

**Pull request merged**
